A few updates to Git pre-commit hook; please copy to `.git/hooks`.

diff --git a/tools/git/hooks/pre-commit b/tools/git/hooks/pre-commit
--- a/tools/git/hooks/pre-commit
+++ b/tools/git/hooks/pre-commit
@@ -63,15 +63,15 @@ else
   versionfile=source/backend/povray.h
 fi
 
-ver_povray_h_3=`sed -n 's/#define [ ]*OFFICIAL_VERSION_STRING [ ]*"\([0-9]*\.[0-9]*\.[0-9]*\)"/\1/p' "$versionfile"`
-ver_povray_h=`sed -n 's/#define [ ]*OFFICIAL_VERSION_STRING [ ]*"\([0-9.]*\)"/\1/p' "$versionfile"`
-ver_povray_h_int=`sed -n 's/#define [ ]*OFFICIAL_VERSION_NUMBER [ ]*\([0-9]*\)/\1/p' "$versionfile"`
-ver_povray_h_hex=`sed -n 's/#define [ ]*OFFICIAL_VERSION_NUMBER_HEX [ ]*\(0x[0]*[0-9]*\)/\1/p' "$versionfile"`
-ver_version_h_major=`sed -n 's/#define [ ]*POV_RAY_MAJOR_VERSION_INT [ ]*\([0-9]*\)/\1/p' "$versionfile"`
-ver_version_h_minor=`sed -n 's/#define [ ]*POV_RAY_MINOR_VERSION_INT [ ]*\([0-9]*\)/\1/p' "$versionfile"`
-ver_version_h_revision=`sed -n 's/#define [ ]*POV_RAY_REVISION_INT [ ]*\([0-9]*\)/\1/p' "$versionfile"`
-ver_version_h_patchlevel=`sed -n 's/#define [ ]*POV_RAY_PATCHLEVEL_INT [ ]*\([0-9]*\)/\1/p' "$versionfile"`
-ver_version_h_prerelease=`sed -n 's/^.*#define [ ]*POV_RAY_PRERELEASE [ ]*"\([^"]*\)".*$/\1/p' "$versionfile"`
+ver_povray_h_3=`sed -n 's/^[ ]*#define [ ]*OFFICIAL_VERSION_STRING [ ]*"\([0-9]*\.[0-9]*\.[0-9]*\)"/\1/p' "$versionfile"`
+ver_povray_h=`sed -n 's/^[ ]*#define [ ]*OFFICIAL_VERSION_STRING [ ]*"\([0-9.]*\)"/\1/p' "$versionfile"`
+ver_povray_h_int=`sed -n 's/^[ ]*#define [ ]*OFFICIAL_VERSION_NUMBER [ ]*\([0-9]*\)/\1/p' "$versionfile"`
+ver_povray_h_hex=`sed -n 's/^[ ]*#define [ ]*OFFICIAL_VERSION_NUMBER_HEX [ ]*\(0x[0]*[0-9]*\)/\1/p' "$versionfile"`
+ver_version_h_major=`sed -n 's/^[ ]*#define [ ]*POV_RAY_MAJOR_VERSION_INT [ ]*\([0-9]*\)/\1/p' "$versionfile"`
+ver_version_h_minor=`sed -n 's/^[ ]*#define [ ]*POV_RAY_MINOR_VERSION_INT [ ]*\([0-9]*\)/\1/p' "$versionfile"`
+ver_version_h_revision=`sed -n 's/^[ ]*#define [ ]*POV_RAY_REVISION_INT [ ]*\([0-9]*\)/\1/p' "$versionfile"`
+ver_version_h_patchlevel=`sed -n 's/^[ ]*#define [ ]*POV_RAY_PATCHLEVEL_INT [ ]*\([0-9]*\)/\1/p' "$versionfile"`
+ver_version_h_prerelease=`sed -n 's/^[ ]*#define [ ]*POV_RAY_PRERELEASE [ ]*"\([^"]*\)".*$/\1/p' "$versionfile"`
 ver_VERSION=`cat unix/VERSION`
 
 if [ x"$ver_povray_h" != x"" ]
@@ -159,13 +159,16 @@ then
       echo "changes to the POV-Ray code detected, updating prerelease id to $prerelease_id."
       if git diff --name-only "$versionfile" | grep "$versionfile" >/dev/null
       then
-        echo "ERROR: Unstaged changes to source/backend/povray.h detected, can't safely update prerelease id."
+        echo "ERROR: Unstaged changes to $versionfile detected, can't safely update prerelease id."
         exit 1
       fi
-      if git diff --name-only "unix/VERSION" | grep "unix/VERSION" >/dev/null
+      if [ -f unix/VERSION ]
       then
-        echo "ERROR: Unstaged changes to unix/VERSION detected, can't safely update prerelease id."
-        exit 1
+        if git diff --name-only "unix/VERSION" | grep "unix/VERSION" >/dev/null
+        then
+          echo "ERROR: Unstaged changes to unix/VERSION detected, can't safely update prerelease id."
+          exit 1
+        fi
       fi
       sed -i \
         -e 's/\(#define [ ]*POV_RAY_PRERELEASE [ ]*".*[^0-9]\)[0-9][0-9]*"/\1'"$prerelease_id"'"/g' \
@@ -275,7 +278,10 @@ do
 
 done
 
-sed_i_fix $stage
+if [ x"$stage" != x"" ]
+then
+  sed_i_fix $stage
+fi
 
 if [ x"$errors" != x"" ]
 then
