Modified povray.h and pre-commit hook for new version numbering scheme.
For official proper releases, POV_RAY_PRERELEASE in povray.h should be undefined, resulting in the version number "X.Y.Z"; unix/VERSION should contain that same string.

For development versions, POV_RAY_PRERELEASE in povray.h should be set to "alpha.NUMBER", which the pre-commit hook will update to "alpha.TIMESTAMP", resulting in the version number "X.Y.Z-alpha.TIMESTAMP";
unix/VERSION should contain the string "X.Y.Z-alpha.NUMBER", which the pre-commit hook will also update to "X.Y.Z-alpha.TIMESTAMP";
if desired, "alpha." might be replaced with any other string; e.g. "beta.NUMBER" would result in the version number "X.Y.Z-beta.TIMESTAMP".

Note that the pre-commit hook script in .git/hooks in your local workspace needs to be replaced with the new version provided in "tools/git/hooks".

diff --git a/tools/git/hooks/pre-commit b/tools/git/hooks/pre-commit
--- a/tools/git/hooks/pre-commit
+++ b/tools/git/hooks/pre-commit
@@ -8,9 +8,10 @@ ver_povray_h=`sed -n 's/#define [ ]*OFFICIAL_VERSION_STRING [ ]*"\([0-9]*\.[0-9]
 ver_povray_h_int=`sed -n 's/#define [ ]*OFFICIAL_VERSION_NUMBER [ ]*\([0-9]*\)/\1/p' source/backend/povray.h`
 ver_povray_h_hex=`sed -n 's/#define [ ]*OFFICIAL_VERSION_NUMBER_HEX [ ]*\(0x[0]*[0-9]*\)/\1/p' source/backend/povray.h`
 ver_VERSION=`cat unix/VERSION`
+prerelease_povray_h=`sed -n 's/^.*#define [ ]*POV_RAY_PRERELEASE [ ]*"\([^"]*\)".*$/\1/p' source/backend/povray.h`
 
 echo "source/backend/povray.h identifies this as version:"
-echo "  $ver_povray_h"
+echo "  $ver_povray_h-$prerelease_povray_h"
 echo "  $ver_povray_h_int"
 echo "  $ver_povray_h_hex"
 
@@ -29,7 +30,7 @@ fi
 echo "unix/VERSION identifies this as version:"
 echo "  $ver_VERSION"
 
-if [ x"$ver_VERSION" != x"$ver_povray_h" ]
+if [ x"$ver_VERSION" != x"$ver_povray_h-$prerelease_povray_h" ]
 then
   echo "MISMATCH."
   exit 1
@@ -37,24 +38,36 @@ fi
 
 ########################################################################################################################
 #
-# Update POV_RAY_REVISION if there is any change to the actual program code.
-# We're setting the revision to the number of minutes since 2000-01-01 00:00.
+# Update prerelease id (trailing numeric portion) if there is any change to the actual program code.
+# We're setting the prerelease id to the number of minutes since 2000-01-01 00:00.
 
 if git diff --cached --name-only | grep -E "^source/|^vfe|^mac|^unix|^windows|^libraries" >/dev/null
 then
-  y2k=`date -u -d"2000-01-01" +"%s"`
-  timestamp=`date -u +"%s"`
-  revision=`expr \( "$timestamp" - "$y2k" \) / 60`
-  echo "changes to the POV-Ray code detected, updating POV_RAY_REVISION to $revision."
-  if git diff --name-only "source/backend/povray.h" | grep "source/backend/povray.h"  >/dev/null
+  if [ x"$prerelease_povray_h" = x"" ]
   then
-    echo "ERROR: Unstaged changes to source/backend/povray.h detected, can't safely update POV_RAY_REVISION."
-    exit 1
+    echo "this does not seem intended to be a prerelease"
+  else
+    y2k=`date -u -d"2000-01-01" +"%s"`
+    timestamp=`date -u +"%s"`
+    revision=`expr \( "$timestamp" - "$y2k" \) / 60`
+    echo "changes to the POV-Ray code detected, updating prerelease id to $revision."
+    if git diff --name-only "source/backend/povray.h" | grep "source/backend/povray.h"  >/dev/null
+    then
+      echo "ERROR: Unstaged changes to source/backend/povray.h detected, can't safely update prerelease id."
+      exit 1
+    fi
+    if git diff --name-only "unix/VERSION" | grep "unix/VERSION" >/dev/null
+    then
+      echo "ERROR: Unstaged changes to unix/VERSION detected, can't safely update prerelease id."
+      exit 1
+    fi
+    sed -i 's/\(#define [ ]*POV_RAY_PRERELEASE [ ]*".*[^0-9]\)[0-9][0-9]*"/\1'"$revision"'"/g' source/backend/povray.h
+    git add source/backend/povray.h
+    sed -i 's/\([^0-9]\)[0-9][0-9]*$/\1'"$revision"'/g' unix/VERSION
+    git add unix/VERSION
   fi
-  sed -i 's/\(#define [ ]*POV_RAY_REVISION [ ]*\)"[^"]*"/\1"'$revision'"/g' source/backend/povray.h
-  git add source/backend/povray.h
 else
-  echo "changes are limited to accompanying files, no need to update POV_RAY_REVISION."
+  echo "changes are limited to accompanying files, no need to update POV_RAY_PRERELEASE."
 fi
 
 ########################################################################################################################
